export const categoryMapping = {
  others: { color: 'bg-gray-200', text: '其他' },
  bar: { color: 'bg-purple-200', text: '酒吧' },
  gym: { color: 'bg-red-200', text: '健身房' },
  exercise: { color: 'bg-orange-200', text: '運動設施' },
  french: { color: 'bg-pink-200', text: '義法餐廳' },
  american: { color: 'bg-blue-200', text: '美式餐廳' },
  sing: { color: 'bg-yellow-300', text: 'KTV' },
  japanese: { color: 'bg-green-300', text: '日式餐廳' },
  read: { color: 'bg-teal-200', text: '閱讀' },
  coffee: { color: 'bg-brown-200', text: '咖啡店' },
  nature: { color: 'bg-green-400', text: '大自然' },
  play: { color: 'bg-yellow-200', text: '反正是玩的' },
  eat: { color: 'bg-red-300', text: '反正是吃的' },
  music: { color: 'bg-purple-300', text: '音樂表演' },
  drama: { color: 'bg-pink-300', text: '戲劇表演' },
  google: { color: 'bg-blue-300', text: 'Google 景點' },
  lodging: { color: 'bg-teal-300', text: '住宿' },
  shopping: { color: 'bg-blue-300', text: '購物' },
  museum: { color: 'bg-orange-300', text: '博物館' },
  park: { color: 'bg-green-300', text: '公園' },
  restaurant: { color: 'bg-red-300', text: '餐廳' },
  store: { color: 'bg-blue-300', text: '商店' },
  supermarket: { color: 'bg-green-300', text: '超市' },
  grocery_or_supermarket: { color: 'bg-green-300', text: '雜貨店/超市' },
  food: { color: 'bg-orange-300', text: '食品' },
  point_of_interest: { color: 'bg-teal-300', text: '景點' },
  establishment: { color: 'bg-yellow-300', text: '機構' },
  transit_station: { color: 'bg-purple-300', text: '交通站' },
  // locality: { color: 'bg-blue-500', text: '地方' },
  political: { color: 'bg-red-300', text: '政治' },
  colloquial_area: { color: 'bg-orange-300', text: '俗名區域' },
  neighborhood: { color: 'bg-green-300', text: '鄰里' },
  department_store: { color: 'bg-blue-300', text: '百貨商店' },
  cafe: { color: 'bg-brown-300', text: '咖啡廳' },
  liquor_store: { color: 'bg-purple-300', text: '酒類商店' },
  place_of_worship: { color: 'bg-yellow-300', text: '宗教場所' },
  // sublocality_level_1: { color: 'bg-green-600', text: '次級地區' },
  // sublocality: { color: 'bg-green-800', text: '次級區域' },
  health: { color: 'bg-rose-200', text: '健康' },
  };

  export const categoryMappingEN= {
    others: { color: 'bg-gray-200', text: '❓ Others' },
    bar: { color: 'bg-purple-200', text: '🍺 Bar' },
    gym: { color: 'bg-red-200', text: '🏋️ Gym' },
    exercise: { color: 'bg-orange-200', text: '🧗 Outdoors' },
    french: { color: 'bg-pink-200', text: '🍝 🧑‍🍳 Italian/French' },
    american: { color: 'bg-blue-200', text: '🍔 American' },
    sing: { color: 'bg-yellow-300', text: '🎤 KTV' },
    japanese: { color: 'bg-green-300', text: '🇯🇵 Japanese' },
    read: { color: 'bg-teal-200', text: '📚 Reading' },
    coffee: { color: 'bg-brown-200', text: '☕️ Coffee Stall' },
    nature: { color: 'bg-green-400', text: '🌳 Nature' },
    play: { color: 'bg-yellow-200', text: '🧑‍🤝‍🧑 Hangout' },
    eat: { color: 'bg-red-300', text: '🥧 snacks' },
    music: { color: 'bg-purple-300', text: '🎵 Music' },
    drama: { color: 'bg-pink-300', text: '🎩 Drama' },
    google: { color: 'bg-blue-300', text: '📌 Google Place' },
    lodging: { color: 'bg-teal-300', text: '🏨 Lodging' },
    shopping: { color: 'bg-blue-300', text: '🛍️ Shopping' },
    museum: { color: 'bg-orange-300', text: '🖼️ Museum' },
    park: { color: 'bg-green-300', text: '⛲️ Park' },
    restaurant: { color: 'bg-red-300', text: '🍴 Restaurant' },
    store: { color: 'bg-blue-300', text: '🏬 Store' },
    supermarket: { color: 'bg-green-300', text: '🍉 Supermarket' },
    grocery_or_supermarket: { color: 'bg-green-300', text: '🚛 Grocery/Supermarket' },
    food: { color: 'bg-orange-300', text: '🍜 Food' },
    point_of_interest: { color: 'bg-teal-300', text: '🎉 Point of Interest' },
    establishment: { color: 'bg-yellow-300', text: '🦦Establishment' },
    transit_station: { color: 'bg-purple-300', text: '🚉 Traffic' },
    // locality: { color: 'bg-blue-500', text: '地方' },
    political: { color: 'bg-red-300', text: '🏢 Politics' },
    colloquial_area: { color: 'bg-orange-300', text: '😆 Colloquial Area' },
    neighborhood: { color: 'bg-green-300', text: '🧑‍🤝‍🧑 Neighborhood' },
    department_store: { color: 'bg-blue-300', text: '🏬 Department Store' },
    cafe: { color: 'bg-brown-300', text: '☕️🔌 Cafe' },
    liquor_store: { color: 'bg-purple-300', text: '🍷 Liquor Store' },
    place_of_worship: { color: 'bg-yellow-300', text: '🙏 Place of Worship' },
    // sublocality_level_1: { color: 'bg-green-600', text: '次級地區' },
    // sublocality: { color: 'bg-green-800', text: '次級區域' },
    health: { color: 'bg-rose-200', text: '🏥 Health' },
    };